import {voluntaryTypes} from "./VoluntaryListType";


export const db: {
  voluntarys: voluntaryTypes[];
} = {

  voluntarys: [
    {
      id: 1,
      name: 'Məlik',
      surname: 'Əlicanov',
      fatherName:'Zakir',
      fin:'6CJ558C',
      birthday:'29.09.1998',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'alicanov98@gmail.com',
      city:'Baki',
      address:'Absheron,Digah,N.Nərimanov, ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '32',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 2,
      name: 'Ərəbov',
      surname: 'Mirsadiq',
      fatherName:'Mirsadiq',
      fin:'1CJ46J',
      birthday:'19.09.2000',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'mirsadiq@gmail.com',
      city:'Baki',
      address:'Absheron,bineqedi,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '32',
      image:'/person2.png',
      position: 'Cari',

    },
    {
      id: 3,
      name: 'Röya',
      surname: 'Abzərova ',
      fatherName:'Mirsadiq',
      fin:'1CJ46J',
      birthday:'19.09.2000',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'abzərova@gmail.com',
      city:'Baki',
      address:'Absheron,bineqedi,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      position: 'Cari',

    },
    {
      id: 4,
      name: 'Əli',
      surname: 'Vahabzadə ',
      fatherName:'Mirsadiq',
      fin:'1CJ46J',
      birthday:'21.03.2001',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'vahabzadə@gmail.com',
      city:'Baki',
      address:'Absheron,bineqedi,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '6',
      dkNumber: '28',
      image:'/person2.png',
      position: 'Cari',

    },
    {
      id: 5,
      name: 'Səriyyə',
      surname: 'Vəliyeva',
      fatherName:'Mirsadiq',
      fin:'1CJ46J',
      birthday:'08.11.1999',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'vəliyeva@gmail.com',
      city:'Baki',
      address:'Absheron,bineqedi,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 6,
      name: 'Gülgəz',
      surname: 'Əliyeva ',
      fatherName:'Mirsadiq',
      fin:'1CJ46J',
      birthday:'28.01.2003',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'əliyeva@gmail.com',
      city:'Baki',
      address:'Absheron,bineqedi,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id:7,
      name: 'Hikmət',
      surname: 'Məmmədov',
      fatherName:'Mirsadiq',
      fin:'1CJ46J',
      birthday:'19.09.2000',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'məmmədov@gmail.com',
      city:'Baki',
      address:'Absheron,bineqedi,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 8,
      name: 'Nicat ',
      surname: 'Melikov ',
      fatherName:'Mirsadiq',
      fin:'1CJ46J',
      birthday:'19.09.2000',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'melikov@gmail.com',
      city:'Baki',
      address:'Absheron,bineqedi,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '6',
      dkNumber: '28',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id:9,
      name: 'Günay',
      surname: 'Abasova',
      fatherName:'Ruslan',
      fin:'1CJ46J',
      birthday:'10.06.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'abasova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Heydər Əliyev ev 5',
      education:'Bakalavr',
      centerNumber: '5',
      dkNumber: '7',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 10,
      name: 'Qurban',
      surname: 'Rəcəbov',
      fatherName:'Tamerlan',
      fin:'1CJ46J',
      birthday:'01.10.2001',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'rəcəbov2001@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 11,
      name: 'İman',
      surname: 'Məmmədov',
      fatherName:'İlham',
      fin:'1CJ46J',
      birthday:'22.02.2002',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'məmmədov@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '41',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 12,
      name: 'Nihad',
      surname: 'Huseynli',
      fatherName:'Kərim',
      fin:'1CJ46J',
      birthday:'22.02.2002',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'huseynli@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 13,
      name: 'Heydər',
      surname: 'Məmmədli',
      fatherName:'Tamerlan',
      fin:'1CJ46J',
      birthday:'23.04.1996',
      gender:'kisi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'məmmədli@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',
 },
    {
      id: 14,
      name: 'Almaz',
      surname: 'Məhərrəmli',
      fatherName:'Nurlan',
      fin:'1CJ46J',
      birthday:'09.07.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'məhərrəmli@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 15,
      name: 'Zəhra',
      surname: 'Fərəcova',
      fatherName:'Akşin',
      fin:'1CJ46J',
      birthday:'17.08.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'fərəcova@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 16,
      name: 'Gülnarə',
      surname: 'Göyçayeva',
      fatherName:'Akif',
      fin:'1CJ46J',
      birthday:'27.10.2003',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'fərəcova@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '2',
      dkNumber: '45',
      image:'/person2.png',
      position: 'Cari',

    },
    {
      id: 17,
      name: 'Aytac ',
      surname: 'Əliyeva',
      fatherName:'Əhməd',
      fin:'1CJ46J',
      birthday:'07.11.2000',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'əliyeva@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',

    },
    {
      id: 18,
      name: 'Elvira',
      surname: 'Əliyeva',
      fatherName:'Ruslan',
      fin:'1CJ46J',
      birthday:'19.12.2001',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'əliyeva@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',

    },
    {
      id: 19,
      name: 'Elnarə',
      surname: 'Rüstəmova',
      fatherName:'Nahid',
      fin:'1CJ46J',
      birthday:'09.11.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'rüstəmova@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 20,
      name: 'Minarə',
      surname: 'Mərdanlı',
      fatherName:'Kamal',
      fin:'1CJ46J',
      birthday:'12.12.2000',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'mərdanlı@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 21,
      name: 'Sevinc',
      surname: 'Mustafayeva',
      fatherName:'Nizami',
      fin:'1CJ46J',
      birthday:'21.09.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'mustafayeva@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 22,
      name: 'Aygül',
      surname: 'Hacızadə',
      fatherName:'Mustafa',
      fin:'1CJ46J',
      birthday:'12.02.2001',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'hacızadə@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 23,
      name: 'Firuzə',
      surname: 'Ağakişiyeva',
      fatherName:'Camal',
      fin:'1CJ46J',
      birthday:'30.01.2001',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'ağakişiyeva@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 24,
      name: 'Aydan',
      surname: 'Məsmalıyeva',
      fatherName:'Mətin',
      fin:'1CJ46J',
      birthday:'03.03.2003',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'məsmalıyeva@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 25,
      name: 'Əsmər',
      surname: 'Yusifova',
      fatherName:'Hikmət',
      fin:'1CJ46J',
      birthday:'30.01.2000',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'yusifova@gmail.com',
      city:'Baki',
      address:'Nizami,Keşlə,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '51',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 26,
      name: 'Nigar',
      surname: 'Əliyeva',
      fatherName:'Fikrət',
      fin:'1CJ46J',
      birthday:'02.03.2003',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'əliyeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 27,
      name: 'Nuray',
      surname: 'Zərbəliyeva',
      fatherName:'Aləm',
      fin:'1CJ46J',
      birthday:'12.05.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'zərbəliyeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '39',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 28,
      name: 'Nergiz',
      surname: 'Nadirli',
      fatherName:'Fəqan',
      fin:'1CJ46J',
      birthday:'22.03.2000',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'nadirli@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '37',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 29,
      name: 'Fərid',
      surname: 'Hacıyev',
      fatherName:'Heydər',
      fin:'1CJ46J',
      birthday:'14.07.2000',
      gender:'Kişi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'hacıyev@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Cari',
    },
    {
      id: 30,
      name: 'Mina',
      surname: 'Talibli',
      fatherName:'Fərid',
      fin:'1CJ46J',
      birthday:'01.03.2003',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'talibli@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '29',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 31,
      name: 'Mehriban',
      surname: 'Cəbrayılova',
      fatherName:'Sadiq',
      fin:'1CJ46J',
      birthday:'30.09.2000',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'cəbrayılova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 32,
      name: 'Aydan',
      surname: 'Məsmalıyeva',
      fatherName:'Qulu',
      fin:'1CJ46J',
      birthday:'23.09.2001',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'məsmalıyeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 33,
      name: 'Cəmilə ',
      surname: 'Hüseynzadə',
      fatherName:'Fazil',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'hüseynzadə@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 34,
      name: 'Gülay',
      surname: 'Əliquliyeva',
      fatherName:'Fazil',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'hüseynzadə@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 35,
      name: 'Nəzrin',
      surname: 'Imanzadə',
      fatherName:'Nurlan',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'imanzadə@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 36,
      name: 'Aygün',
      surname: 'Lətifova',
      fatherName:'Kərim',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'lətifova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 37,
      name: 'Roza',
      surname: 'Məmmədova',
      fatherName:'Hikmət',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'məmmədova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '5',
      dkNumber: '13',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 38,
      name: 'Həsən',
      surname: 'Əzizov',
      fatherName:'Tərlan',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Kişi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'hüseynzadə@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '2',
      dkNumber: '45',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 39,
      name: 'Mehriban',
      surname: 'Cəbrayılova',
      fatherName:'Ayaz',
      fin:'1CJ46J',
      birthday:'15.09.2000',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'cəbrayılova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 40,
      name: 'Səbinə ',
      surname: 'Zeynalova',
      fatherName:'Yaşar',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'zeynalova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 41,
      name: 'Leyla',
      surname: 'Ağayeva',
      fatherName:'Fazil',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'ağayeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '2',
      dkNumber: '34',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 42,
      name: 'Fərid',
      surname: 'Hacıyev',
      fatherName:'Sadiq',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Kişi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'hacıyev@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 43,
      name: 'Zərifə',
      surname: 'Cabbarlı',
      fatherName:'İsrafil',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'cabbarlı@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 44,
      name: 'Gulebeste',
      surname: 'Hüseynova',
      fatherName:'Alim',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'huseynova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 45,
      name: 'Günel',
      surname: 'Hüseynova',
      fatherName:'Asif',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'huseynova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 46,
      name: 'Elvira ',
      surname: 'Əliyeva',
      fatherName:'Akif',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'eliyeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Cari',

    },
    {
      id: 47,
      name: 'Mehriban',
      surname: 'Cəbrayılova',
      fatherName:'Amal',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'cebrayılova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 48,
      name: 'Səbinə',
      surname: 'Zeynalova',
      fatherName:'Ramal',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'zeynalova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 49,
      name: 'Nigar',
      surname: 'Musayeva',
      fatherName:'Rafiq',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'musayeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '58',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 50,
      name: 'Könül ',
      surname: 'Seyidbeyli',
      fatherName:'Hakim',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'seyidbeyli@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 51,
      name: 'Aytac',
      surname: 'Osmanova',
      fatherName:'Zamiq',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'osmanova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 52,
      name: 'Aytac',
      surname: 'Əliyeva',
      fatherName:'Kamil',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'eliyeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '2',
      dkNumber: '45',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 53,
      name: 'Samirə',
      surname: 'Cəbrayılova',
      fatherName:'Xaliq',
    fin:'1CJ46J',
    birthday:'05.04.2002',
    gender:'Qadın',
    phone:'0507705055',
    language:'ENG,RUS,TR',
    email:'cebrayılova@gmail.com',
    city:'Baki',
    address:'Nərimanov,Nizami Gencevi ev 5',
    education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '34',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 54,
      name: 'Zülfiyyə',
      surname: 'Yeylaqaliyeva',
      fatherName:'Kərim',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'yeylaqaliyeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 55,
      name: 'Afiqa',
      surname: 'Cabbarova',
      fatherName:'Zakir',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'cabbarova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '5',
      dkNumber: '13',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 56,
      name: 'Könül ',
      surname: 'Seyidbeyli',
      fatherName:'Ülfət',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'seyidbeyli@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 57,
      name: 'Gülnaz',
      surname: 'Ağayeva',
      fatherName:'Anar',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'ağayeva@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 58,
      name: 'Mirsadiq',
      surname: 'Ərəbov',
      fatherName:'Faiq',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Kişi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'mirsadiq@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '3',
      dkNumber: '38',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 59,
      name: 'Leyla',
      surname: 'Süleymanova',
      fatherName:'Fuad',
      fin:'1CJ46J',
      birthday:'05.04.2002',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'süleymanova@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Məzun',
    },
    {
      id: 60,
      name: 'Sayalı',
      surname: 'Abbaszadə',
      fatherName:'Fəhmin',
      fin:'1CJ46J',
      birthday:'12.05.2003',
      gender:'Qadın',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'abbaszadə@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      position: 'Məzun',

    },
    {
      id: 61,
      name: 'Nurlan',
      surname: 'Balayev',
      fatherName:'Cabir',
      fin:'1CJ46J',
      birthday:'15.10.2000',
      gender:'Kişi',
      phone:'0507705055',
      language:'ENG,RUS,TR',
      email:'balayev@gmail.com',
      city:'Baki',
      address:'Nərimanov,Nizami Gencevi ev 5',
      education:'Bakalavr',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      position: 'Məzun',
    },
  ],
};
