import {voluntaryTypes} from "./VoluntaryListType";


export const db: {
  voluntarys: voluntaryTypes[];
} = {

  voluntarys: [
    {
      id: 1,
      name: 'Məlik',
      surname: 'Əlicanov',
      centerNumber: '4',
      dkNumber: '32',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',

    },
    {
      id: 2,
      name: 'Ərəbov',
      surname: 'Mirsadiq',
      centerNumber: '3',
      dkNumber: '32',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',

    },
    {
      id: 3,
      name: 'Röya',
      surname: 'Abzərova ',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',

    },
    {
      id: 4,
      name: 'Əli',
      surname: 'Vahabzadə ',
      centerNumber: '6',
      dkNumber: '28',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',

    },
    {
      id: 5,
      name: 'Səriyyə',
      surname: 'Vəliyeva',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',

    },
    {
      id: 6,
      name: 'Gülgəz',
      surname: 'Əliyeva ',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',

    },
    {
      id:7,
      name: 'Hikmət',
      surname: 'Məmmədov',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',
    },
    {
      id: 8,
      name: 'Nicat ',
      surname: 'Melikov ',
      centerNumber: '6',
      dkNumber: '28',
      image:'/person2.png',
      club: 'Xarici dil klubu',
      position: 'Cari',
    },
    {
      id:9,
      name: 'Günay',
      surname: 'Abasova',
      centerNumber: '5',
      dkNumber: '7',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
    },
    {
      id: 10,
      name: 'Qurban',
      surname: 'Rəcəbov',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
    },
    {
      id: 11,
      name: 'Məmmədov',
      surname: 'İman',
      centerNumber: '3',
      dkNumber: '41',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
    },
    {
      id: 12,
      name: 'Huseynli',
      surname: 'Nihad',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
    },
    {
      id: 13,
      name: 'Heydər',
      surname: 'Məmmədli',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
 },
    {
      id: 14,
      name: 'Almaz',
      surname: 'Məhərrəmli',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
    },
    {
      id: 15,
      name: 'Zəhra',
      surname: 'Fərəcova',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
    },
    {
      id: 16,
      name: 'Gülnarə',
      surname: 'Göyçayeva',
      centerNumber: '2',
      dkNumber: '45',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',

    },
    {
      id: 17,
      name: 'Aytac ',
      surname: 'Əliyeva',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',

    },
    {
      id: 18,
      name: 'Elvira',
      surname: 'Əliyeva',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',

    },
    {
      id: 19,
      name: 'Elnarə',
      surname: 'Rüstəmova',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      club: 'Kitab klubu',
      position: 'Cari',
    },
    {
      id: 20,
      name: 'Minarə',
      surname: 'Mərdanlı',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 21,
      name: 'Sevinc',
      surname: 'Mustafayeva',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 22,
      name: 'Aygül',
      surname: 'Hacızadə',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 23,
      name: 'Firuzə',
      surname: 'Ağakişiyeva',
      centerNumber: '4',
      dkNumber: '34',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 24,
      name: 'Aydan',
      surname: 'Məsmalıyeva',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 25,
      name: 'Əsmər',
      surname: 'Yusifova',
      centerNumber: '1',
      dkNumber: '51',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 26,
      name: 'Nigar',
      surname: 'Əliyeva',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 27,
      name: 'Nuray',
      surname: 'Zərbəliyeva',
      centerNumber: '1',
      dkNumber: '39',
      image:'/person2.png',
      club: 'Yaradıcılıq klubu',
      position: 'Cari',
    },
    {
      id: 28,
      name: 'Nergiz',
      surname: 'Nadirli',
      centerNumber: '1',
      dkNumber: '37',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Cari',
    },
    {
      id: 29,
      name: 'Fərid',
      surname: 'Hacıyev',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Cari',
    },
    {
      id: 30,
      name: 'Mina',
      surname: 'Talibli',
      centerNumber: '1',
      dkNumber: '29',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Cari',
    },
    {
      id: 31,
      name: 'Mehriban',
      surname: 'Cəbrayılova',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Məzun',
    },
    {
      id: 32,
      name: 'Aydan',
      surname: 'Məsmalıyeva',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Məzun',
    },
    {
      id: 33,
      name: 'Cəmilə ',
      surname: 'Hüseynzadə',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Məzun',
    },
    {
      id: 34,
      name: 'Gülay',
      surname: 'Əliquliyeva',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Məzun',
    },
    {
      id: 35,
      name: 'Nəzrin',
      surname: 'Imanzadə',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      club: 'Filim klubu',
      position: 'Məzun',
    },
    {
      id: 36,
      name: 'Aygün',
      surname: 'Lətifova',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 37,
      name: 'Roza',
      surname: 'Məmmədova',
      centerNumber: '5',
      dkNumber: '13',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 38,
      name: 'Həsən',
      surname: 'Əzizov',
      centerNumber: '2',
      dkNumber: '45',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 39,
      name: 'Mehriban',
      surname: 'Cəbrayılova',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 40,
      name: 'Səbinə ',
      surname: 'Zeynalova',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 41,
      name: 'Leyla',
      surname: 'Ağayeva',
      centerNumber: '2',
      dkNumber: '34',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 42,
      name: 'Fərid',
      surname: 'Hacıyev',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 43,
      name: 'Zərifə',
      surname: 'Cabbarlı',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',
    },
    {
      id: 44,
      name: 'Gulebeste',
      surname: 'Huseynova',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',

    },
    {
      id: 45,
      name: 'Günel',
      surname: 'Hüseynova',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Məzun',

    },
    {
      id: 46,
      name: 'Elvira ',
      surname: 'Əliyeva',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Fərdi inkişaf klubu',
      position: 'Cari',

    },
    {
      id: 47,
      name: 'Mehriban',
      surname: 'Cəbrayılova',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',

    },
    {
      id: 48,
      name: 'Səbinə',
      surname: 'Zeynalova',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',

    },
    {
      id: 49,
      name: 'Nigar',
      surname: 'Musayeva',
      centerNumber: '1',
      dkNumber: '58',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',

    },
    {
      id: 50,
      name: 'Könül ',
      surname: 'Seyidbeyli',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',
    },
    {
      id: 51,
      name: 'Aytac',
      surname: 'Osmanova',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',
    },
    {
      id: 52,
      name: 'Aytac',
      surname: 'Əliyeva',
      centerNumber: '2',
      dkNumber: '45',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',
    },
    {
      id: 53,
      name: 'Samirə',
      surname: 'Cəbrayılova',
      centerNumber: '3',
      dkNumber: '34',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',
    },
    {
      id: 54,
      name: 'Zülfiyyə',
      surname: 'Yeylaqaliyeva',
      centerNumber: '6',
      dkNumber: '30',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',
    },
    {
      id: 55,
      name: 'Afiqa',
      surname: 'Cabbarova',
      centerNumber: '5',
      dkNumber: '13',
      image:'/person2.png',
      club: 'Natiqlik klubu',
      position: 'Məzun',
    },
    {
      id: 56,
      name: 'Könül ',
      surname: 'Seyidbeyli',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Şahmat klubu',
      position: 'Məzun',
    },
    {
      id: 57,
      name: 'Gülnaz',
      surname: 'Ağayeva',
      centerNumber: '3',
      dkNumber: '42',
      image:'/person2.png',
      club: 'Şahmat klubu',
      position: 'Məzun',
    },
    {
      id: 58,
      name: 'Ərəbov',
      surname: 'Mirsadiq',
      centerNumber: '3',
      dkNumber: '38',
      image:'/person2.png',
      club: 'Şahmat klubu',
      position: 'Məzun',
    },
    {
      id: 59,
      name: 'Leyla',
      surname: 'Süleymanova',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Şahmat klubu',
      position: 'Məzun',
    },
    {
      id: 60,
      name: 'Sayalı',
      surname: 'Abbaszadə',
      centerNumber: '1',
      dkNumber: '57',
      image:'/person2.png',
      club: 'Şahmat klubu',
      position: 'Məzun',

    },
    {
      id: 61,
      name: 'Nurlan',
      surname: 'Balayev',
      centerNumber: '4',
      dkNumber: '33',
      image:'/person2.png',
      club: 'Şahmat klubu',
      position: 'Məzun',
    },
  ],
};
